server:
  port: 9999
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          pamiadu:
            require-authorization-consent: true
            registration:
              client-id: pamiadu
              client-secret: '{bcrypt}$2a$10$RhLDi5hKxNqBQcSkfRdIUemy9NGGKZZ/0J7y4BDNJbPtKYcZEgTnC'
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://127.0.0.1:8081/login/oauth2/code/spring
                - http://127.0.0.1:8081/
              scopes:
                - user.read
                - user.write
                - openid
              client-authentication-methods: client_secret_basic
        issuer: http://localhost:9999
logging:
  level:
    root: info
    org.springframework.security: debug
