server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    root: info
#    org.springframework.security: debug
