server:
  port: 9999
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          pamiadu:
            require-authorization-consent: true
            registration:
              client-id: pamiadu
              client-secret: pamiadu
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://127.0.0.1:8081/login/oauth2/code/pamiadu
              scopes:
                - user.read
                - user.write
                - openid
              client-authentication-methods:
                - client_secret_basic
